# Generated by Django 3.1 on 2023-01-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='status',
            new_name='is_active',
        ),
    ]
