# Generated by Django 3.1 on 2023-01-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('cart', '0002_auto_20230105_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
