# Generated by Django 3.1 on 2023-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('order', '0002_auto_20230120_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
